{% set name = "restic" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/restic/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a9c88d5288ce04a6cc78afcda7590d3124966dab3daa9908de9b3e492e2925fb

build:
  number: 1

requirements:
  build:
    - {{ compiler('go') }} 1.17

test:
  commands:
    - which restic  # [not win]
    - where restic  # [win]
    - restic version

about:
  home: https://restic.net/
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - licenses/
  summary: Restic is a fast and secure backup program.
  description: |
    Restic is a modern backup program that can back up your files from Linux,
    BSD, Mac and Windows to many different storage types, including self-hosted
    and online services easily, being a single executable that you can run
    without a server or complex setup effectively, only transferring the parts
    that actually changed in the files you back up securely, by careful use of
    cryptography in every part of the process verifiably, enabling you to make
    sure that your files can be restored when needed freely - restic is
    entirely free to use and completely open source
  doc_url: https://restic.readthedocs.io/en/stable/index.html
  dev_url: https://github.com/restic/restic.git

extra:
  recipe-maintainers:
    - anjos
    - lsetiawan
